repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
  -   repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
      - id: black
        language_version: python3.7
  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.14.0
      hooks:
      -   id: reorder-python-imports
          args: [--py3-plus]