version: '3.3'

services:
  mysql:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pymatcha
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql-net

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile.celery
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    links:
      - redis
    networks:
      - redis-net
      - mysql-net

  web:
    container_name: pymatcha
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:5000"
    volumes:
      - pymatcha:/app
    depends_on:
      - "mysql"
      - "redis"
      - "worker"
    links:
      - mysql
      - redis
      - worker
    networks:
      - redis-net
      - mysql-net
      - web-net

  nginx:
    image: nginx:latest
    container_name: pnginx
    volumes:
      - ./nginx/:/etc/nginx/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - web-net

networks:
  redis-net:
  mysql-net:
  web-net:

volumes:
  redis-data:
  mysql:
  pymatcha:
