FROM python:3.7

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true
ENV PYTHONUNBUFFERED 1

COPY . /queue
WORKDIR /queue

RUN apt-get install gcc

RUN pip install -r backend/requirements.txt

ENTRYPOINT export $(cat .env | xargs) && celery worker --workdir backend -A PyMatcha.celery -B --loglevel=debug